### ISSUE TITLE
Download the dataset under windows.

### ISSUE THREAD

**Issue by noUmbrella** [SilvioGiancola/TrackingNet-devkit#1]
Is there any method to download this dataset under windows?

**Comment by SilvioGiancola** [comment]
Hi @noUmbrella , 
Have you tried to download the dataset on Windows? have you encounter any issue, error or bug?
All the code is written on python3 hence should work on Windows too. If you have any issue with the Anaconda environment, you can create it for windows from scratch using `conda create -n TrackingNet python=3 requests pandas tqdm numpy` and `activate TrackingNet`. If there is a specific error in the code, please report it here and I will help you find a solution.
Cheers,

**Comment by noUmbrella** [comment]
Thank you for your apply. I have downed it successfully. Thank you for your remarkable job.

在2018-09-19 20:11:54，SilvioGiancolanotifications@github.com写道：

Hi @noUmbrella ,
Have you tried to download the dataset on Windows? have you encounter any issue, error or bug?
All the code is written on python3 hence should work on Windows too. If you have any issue with the Anaconda environment, you can create it for windows from scratch using conda create -n TrackingNet python=3 requests pandas tqdm numpy and activate TrackingNet. If there is a specific error in the code, please report it here and I will help you find a solution.
Cheers,
