### ISSUE TITLE
About the pretraining experiment for SiamFC in the paper

### ISSUE THREAD

**Issue by handworker** [SilvioGiancola/TrackingNet-devkit#11]
HI, Dr. M¨uller,
Thanks for your great work. I am confused that how do you select one of the twelve chunks (2511 videos) to retrain SiamFC? Do you randomly select one of the twelve chunks videos in each class? Looking forward to your detailed description.

**Comment by thias15** [comment]
Hello @handworker. 

We just picked the first junk out of the twelve. The idea was just to show the benefit of the additional data. We would expect even better results if more junks are used.

**Comment by handworker** [comment]
When I download the dataset, I find the answer. There are several chunks in the data. Many thanks for your reply.

**Comment by bamboopu** [comment]
> Hello @handworker.
> 
> We just picked the first junk out of the twelve. The idea was just to show the benefit of the additional data. We would expect even better results if more junks are used.

Thanks for your sharing. As a personal researcher, I was scared by the scale of the dataset for many years. Now I know that only the first junk was used.
