### ISSUE TITLE
There is no YAML file in zip you uploaded

### ISSUE THREAD

**Issue by makalo** [SilvioGiancola/TrackingNet-devkit#12]
Thank you very much for your work. When I zip the result of the test set and upload it, it shows "There is no YAML file in zip you uploaded"

**Comment by SilvioGiancola** [comment]
Have a look at the [code](https://github.com/SilvioGiancola/TrackingNet-devkit/blob/master/metrics.py) for the metrics, it's the same code running on the server, if it runs on your workstation, it will run on the server.

Also check the [dummy_submission.zip](https://github.com/SilvioGiancola/TrackingNet-devkit/blob/master/dummy_subm.zip) to see how the results are organized. You may have an extra folder within your compressed zip that should not be there and impede a proper reading of your results. 

Also check that your results are in a csv format with commas between each value, and 1 BB (4 values) per line.

**Comment by makalo** [comment]
Thank you for your reply. I have checked the result according to the method you said, but I can't find the problem. I have provided my [https://drive.google.com/open?id=1k3SrTktaJsChygLdraiqM43uJdg2jEmY](result)  in Google Drive  Could you see if there is any problem?

**Comment by SilvioGiancola** [comment]
I was able to submit your exact results on the [server](http://eval.tracking-net.org/web/challenges/challenge-page/39/overview), without any issue. Please try again, I couldn't reproduce your issue.

**Comment by SilvioGiancola** [comment]
Hi, could you please end me a screenshot of your error?
PS: by trying myself your submission on the server I got your results:
```
        Precision 66.4294402491
        NormalizedPrecision 78.844017693
        Success 72.6283813851
```
Do you still have your error message?

**Comment by makalo** [comment]
Hi,Thank you very much for your reply. I'm glad you can provide the evaluation results. But&nbsp; there is still problem. The screenshot of this problem is in the attachment of the email.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xujiao3628"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月3日(星期天) 下午2:42
收件人:&nbsp;"SilvioGiancola/TrackingNet-devkit"<TrackingNet-devkit@noreply.github.com&gt;;
抄送:&nbsp;"Makalo"<1647855685@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SilvioGiancola/TrackingNet-devkit] There is no YAML file in zip you uploaded (#12)




Hi, could you please end me a screenshot of your error?
 PS: by trying myself your submission on the server I got your results:
         Precision 66.4294402491         NormalizedPrecision 78.844017693         Success 72.6283813851  
Do you still have your error message?

**Comment by SilvioGiancola** [comment]
I have not received any attachment. Please connect with us on [SLACK](https://join.slack.com/t/tracking-net/shared_invite/enQtNTYxNTEyMjYwMTQ0LTEyYmYxM2E5NzViZWRmYTU2ODI4ZGIyYTMwOWRkMDQ0YjljZmQzYmRjNGM4MjVjZTdlN2UwNTg5MDRkOTJhODk) or send me the attachment in an new email (you can find my email address from the paper, you should be able to infer it from my name).
