### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by iminfine** [SilvioGiancola/TrackingNet-devkit#15]
I face the problem as downloading about 50 files:
Permission denied: https://drive.google.com/uc?id=<ID>, Maybe you need to change permission over 'Anyone with the link'?
And it will be normal 3 hours later with the same IP, while other IPs are normal but still can not download more than 50 files which means this problem is not just an exception. 
What a pain! It seems that will take me a few months to get the training data on a cluster😂😂😂.

Could you please fix this problem or provide big zip files(make one chunk as a zip file)?

**Comment by lemmersj** [comment]
This is addressed in #2 . The developer response is that Google drive has a download limit that keeps getting exceeded. That doesn't help you download the dataset, but that's what's going on.

For the record, I gave up on downloading it about a month ago after a week of trying. I was just checking to see if someone had uploaded a mirror yet. Perhaps someday :smile: .

**Comment by iminfine** [comment]
> This is addressed in #2 . The developer response is that Google drive has a download limit that keeps getting exceeded. That doesn't help you download the dataset, but that's what's going on.
> 
> For the record, I gave up on downloading it about a month ago after a week of trying. I was just checking to see if someone had uploaded a mirror yet. Perhaps someday 😄 .

You should keep trying. Sometimes, I could download hundreds of files. Finally, I got what I need (Test data and Train0 to Train3) last week.
