### ISSUE TITLE
Did someone upload to baidu network disk?

### ISSUE THREAD

**Issue by hlyj1995** [SilvioGiancola/TrackingNet-devkit#18]
The dataset is so large,my VPN only supports me download two packets.I hope someone can upload to baidu network disk.Thanks.

**Comment by SilvioGiancola** [comment]
We are currently experimenting a bittorrent solution to share TrackingNet among the tracking community. The torrent is available on [https://academictorrents.com/details/1faf1b53cc0099d2206f02be42b5688952c3c6b3](https://academictorrents.com/details/1faf1b53cc0099d2206f02be42b5688952c3c6b3).

It may be very slow at the beginning, but it will improve once more people will require the a copy. Here are some guidelines:
 - I hope everyone will play fair and seed its torrent as we are currently doing.
 - Feel free to share the torrent between colleagues, seedbox or mirroring server.
 - The google drive backup links [[link1](https://drive.google.com/drive/u/2/folders/1gJOR-r-jPFFFCzKKlMOW80WFtuaMiaf6)] [[link2](https://drive.google.com/drive/u/2/folders/1xrxlI6otQvWlRJjsX1pddZBY9h2WbmVi)] are still available, but capped in daily bandwidth .
 - If you already have downloaded a chunk from the backup links, please put it in the output folder of your torrent: it won't download it again and will save you precious download time.

**Comment by SilvioGiancola** [comment]
@hlyj1995 Once you downloaded it, feel free to put a copy on the baidu network and share it here.
