### ISSUE TITLE
how to use the  evaluation server

### ISSUE THREAD

**Issue by meimeixu520** [SilvioGiancola/TrackingNet-devkit#20]
hi,thanks for you brilliant work.Now  i  have  the results about the trackingnet,but i don't use the evaluation server,can you give me some advices?Thank you very much. Looking forward to your reply.

**Comment by SilvioGiancola** [comment]
You sign up to the evaluation website http://eval.tracking-net.org/ and submit your results. all information are provided there.

**Comment by meimeixu520** [comment]
Thanks for your reply,i have signned  up and logged in successfully,but i don't find the submit button.And do the results need to change the format? Looking forward to your reply.
