### ISSUE TITLE
Evaluation Server Failure

### ISSUE THREAD

**Issue by zhengjilai** [SilvioGiancola/TrackingNet-devkit#25]
Hi. Recently we are working on object tracking and need evaluation result on TrackingNet.  However, we cannot login on the evaluation server of TrackingNet from few days ago, and there have been some other researchers reporting similar question to us. May you please check the server please? The submission deadline is just around the corner. Thank you.

**Comment by deneb2016** [comment]
I have same problem..
Please check the evaluation server.

**Comment by SilvioGiancola** [comment]
The evaluation server went down, we are working on it, stay tuned. 
We are aware of ICCV deadline and will find a solution ASAP.

**Comment by SilvioGiancola** [comment]
The evaluation server is back online, you can login again and send your submission.
Just in time for your deadline :)

**Comment by zhengjilai** [comment]
> The evaluation server is back online, you can login again and send your submission.
> Just in time for your deadline :)

I tried that and succeeded 3 minutes ago. Thank you for your great work.
