### ISSUE TITLE
Eval server couldn't upload result

### ISSUE THREAD

**Issue by Soarkey** [SilvioGiancola/TrackingNet-devkit#28]
Hi, I try to test my tracker, but eval server couldn't upload result.
please see this issue!
thanks

**Comment by SilvioGiancola** [comment]
It should be working, I saw submissions no later than 5 min ago.

**Comment by Soarkey** [comment]
ok, I already fixed this issue by connecting my phone hotspot network.
I think it may be related to the campus network.

Thanks for your response! 😁
