### ISSUE TITLE
missing zips on TRAIN_10

### ISSUE THREAD

**Issue by SangbumChoi** [SilvioGiancola/TrackingNet-devkit#29]
As the title mentions I think there is a missing zip file in TRAIN_10

RuntimeError: [Errno 2] No such file or directory: '/mnt/nas_2/Data/PublicDB/Trackingnet/TRAIN_10/frames/ekw22HGT0TY_0/214.jpg'

I can't find ekw22HGToTY_0.zip in TRAIN_10 folder

Also when I use download.py 
```
from TrackingNet.Downloader import TrackingNetDownloader
from TrackingNet.utils import getListSplit


downloader = TrackingNetDownloader(LocalDirectory="./")

for split in getListSplit():
    if split != 'TRAIN_10':
        continue
    downloader.downloadSplit(split)
```

following 404 error occurs once

Downloading TRAIN_10...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████▋| 91.9G/92.1G [00:13<00:00, 6.28GiB/s]HTTP Error 404: Not Found
Downloading TRAIN_10...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████▉| 92.1G/92.1G [00:17<00:00, 5.34GiB/s]

Can you confirm this error?

**Comment by SangbumChoi** [comment]
I confirmed that backup link has the missing file though 👍🏼

**Comment by SilvioGiancola** [comment]
Hi @SangbumChoi Thank you for spotting that issue, I have fixed it, you can now download it again with pip :)
Cheers,
