### ISSUE TITLE
Evaluate the results

### ISSUE THREAD

**Issue by f1064531335** [SilvioGiancola/TrackingNet-devkit#30]
I can log in. But when I click "All challenge"-“View Details”, I just get “Unable to create or select a team. Please verify your email first!”. And I can't find any button to try to verification. 
![20220614111922](https://user-images.githubusercontent.com/56526839/173486581-586f0acd-e6d6-46f2-a500-f4fc8244652c.png)

**Comment by Jiangsiping** [comment]
I had the same problem, have you solved it?

**Comment by f1064531335** [comment]
Sorry, I don't solve it.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 25, 2022 15:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SilvioGiancola/TrackingNet-devkit] Evaluate the results (Issue#30)




 
I had the same problem, have you solved it?

**Comment by SilvioGiancola** [comment]
Can you please try to sign up / log in on http://eval.tracking-net.org/ instead of https://eval.tracking-net.org/?

Alternatively please check your spam for any verification email.

**Comment by f1064531335** [comment]
Thank you. I'll have a try using http and check my spam again.
I tried sign in on http, with fengzh2022@qq.com and guoyi4948@gmail.com. There is no new email sent to me and no verification email in my spam. Then, I tried to sign up on http website. When I entered my email and password and click the "sign up", the website didn't give response. And when I click it again, the website give "A user with that username already exists." There is no prompt for verification.
Thank you again. I'll ask someone who successfully signed up. If it's convenient, please properly handle the following email accounts. I don't have any more email addresses. 
1064531335@qq.com
fengzh2022@qq.com
guoyi4948@gmail.com
guoyi4948@163.com

**Comment by f1064531335** [comment]
I can participate this challenge, signing up on https://eval.ai/auth/login. Thank you.

**Comment by f1064531335** [comment]
I can participate this challenge, signing up on https://eval.ai/auth/login. I used my previously registered account on the original website and my school email. It seems that the challenge has been merged into another website.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilvioGiancola/TrackingNet-devkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月25日(星期六) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SilvioGiancola/TrackingNet-devkit] Evaluate the results (Issue #30)





 
I had the same problem, have you solved it?

**Comment by SilvioGiancola** [comment]
This is the link for the new evaluation server: https://eval.ai/web/challenges/challenge-page/1805/overview

**Comment by SilvioGiancola** [comment]
You will need to create a new account altogether.
