### ISSUE TITLE
Missing TRAIN_4/zips/BbnxzNL5tMk_0.zip

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [SilvioGiancola/TrackingNet-devkit#32]
Hi,

It seems `TRAIN_4/zips/BbnxzNL5tMk_0.zip`  is missing from NextCloud. This file does exist in `TRAIN_4.zip` though.

Best,
Rémi

**Comment by SilvioGiancola** [comment]
Hi @RemiLacroix-IDRIS 
Do you mean OwnCloud? I am not aware of any link from NextCloud. 
Thanks for the report.

**Comment by RemiLacroix-IDRIS** [comment]
Yes, sorry I meant OwnCloud (https://exrcsdrive.kaust.edu.sa namely).

**Comment by SilvioGiancola** [comment]
Good catch! I believe the upload failed for this particular file. I have uploaded it again, please give it a try now and let me know if you find any other discrepancy in the future. Cheers!

**Comment by RemiLacroix-IDRIS** [comment]
Thanks, as far as I can tell there are no other files missing.
