### ISSUE TITLE
Sorry, the participant team is not approved by host yet.

### ISSUE THREAD

**Issue by wsumel** [SilvioGiancola/TrackingNet-devkit#35]
Hi, I am using the trackingnet to test the performance of my newly built tracker. But I can't submit test results in eval ai. The website says "Sorry, the participant team is not approved by host yet."

**Comment by wsumel** [comment]
@SilvioGiancola Can you help？, thanks very much！！！

**Comment by SilvioGiancola** [comment]
Hi @wsumel, I think you need to complete the registration of your team or your account on [eval.ai](http://eval.ai/). I don’t have to approve your team for you to send your results on [eval.ai](http://eval.ai/). It has been running for 5 years now and I never had to approve a team before. Best,

**Comment by SilvioGiancola** [comment]
I followed up with the admins of eval.ai, they told me they pushed a new feature, but that should not apply to the trackingnet evaluation server. If you face this issue, you can fix it by cleaning your cache or loging in in incognito mode. Cheers
