### ISSUE TITLE
Invalid URL '': No scheme supplied. Perhaps you meant http://?

### ISSUE THREAD

**Issue by CHYjeremy** [SilvioGiancola/TrackingNet-devkit#36]
Hi authors of TrackingNet,

Much appreciate for your work. 

however i am faced an error as described in title.

bg: i am operating on an remote host with Ubuntu 22.04, nothing else different.

when i "python download_TrackingNet.py", the above error shows...

Any suggestions?

**Comment by CHYjeremy** [comment]
anyone can help pls?

**Comment by SilvioGiancola** [comment]
Have you tried with the pip package? https://pypi.org/project/TrackingNet/

**Comment by CHYjeremy** [comment]
Yes i do, and it worked, thx!
