### ISSUE TITLE
Having  some wrong  with  ssl。

### ISSUE THREAD

**Issue by haha94322** [SilvioGiancola/TrackingNet-devkit#4]
Thank you for your work on this project !   
When i running the “download_TrackingNet.py”.Always have wrong with “ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)”.
because i ues the vpn to run this code, so i can not to change the ip and the agent.Whould you like to give me some advice?
Hoping for your reply !

**Comment by huangbiubiu** [comment]
Similar problem:
```
Traceback (most recent call last):
  File "/home/***/anaconda3/envs/TrackingNet/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/***/anaconda3/envs/TrackingNet/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:748)

```

Are there any workarounds?

**Comment by SilvioGiancola** [comment]
We believe this issue originates from Google drive servers and the limitation to 10TB per day. Please retry later and let us know if you still have this issue
