### ISSUE TITLE
Is it possible to obtain category information?

### ISSUE THREAD

**Issue by wgting96** [SilvioGiancola/TrackingNet-devkit#8]
Hi, is there any possible way to obtain the category information for echo sequence? 
The raw YoutubeBB dataset should have 23 classes, but I could not find the corresponding raw annotations in YoutubeBB.

**Comment by SilvioGiancola** [comment]
Hi @wgting96 , we do not want to share the category information for each sequences since it breaks the rules of "Generic Object Tracking". If we provide the category name, one can simply use a detector to output a bounding box at each frame.
